set(IGNITECOMPILER_C_EXAMPLE_TARGET IgniteCompilerCExample)

add_executable(${IGNITECOMPILER_C_EXAMPLE_TARGET}
	${CMAKE_CURRENT_LIST_DIR}/C_Example.c
)

target_include_directories(${IGNITECOMPILER_C_EXAMPLE_TARGET} PRIVATE
	${CMAKE_CURRENT_LIST_DIR}/../Source
)

target_link_libraries(${IGNITECOMPILER_C_EXAMPLE_TARGET} PRIVATE IgniteCompiler)

set_target_properties(${IGNITECOMPILER_C_EXAMPLE_TARGET} PROPERTIES
	RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/Example
)

if (MSVC)
	set_property(TARGET ${IGNITECOMPILER_C_EXAMPLE_TARGET} PROPERTY
		VS_DEBUGGER_WORKING_DIRECTORY "$<TARGET_FILE_DIR:${IGNITECOMPILER_C_EXAMPLE_TARGET}>"
	)
endif()

add_custom_command(TARGET ${IGNITECOMPILER_C_EXAMPLE_TARGET} POST_BUILD
	COMMAND ${CMAKE_COMMAND} -E copy_directory
		${CMAKE_CURRENT_LIST_DIR}/Shaders
		$<TARGET_FILE_DIR:${IGNITECOMPILER_C_EXAMPLE_TARGET}>/Shaders
	COMMENT "Copying shader examples for C example runtime"
)

if (WIN32)
	add_custom_command(TARGET ${IGNITECOMPILER_C_EXAMPLE_TARGET} POST_BUILD
		COMMAND ${CMAKE_COMMAND} -E copy_if_different
			$<TARGET_FILE:IgniteCompiler>
			$<TARGET_FILE_DIR:${IGNITECOMPILER_C_EXAMPLE_TARGET}>/
		COMMENT "Copying IgniteCompiler runtime next to C example"
	)
endif()
