# Copyright (c) 2026 Evangelion Manuhutu

set(IGNITECOMPILER_CPP_EXAMPLE_TARGET IgniteCompilerCPPExample)

add_executable(${IGNITECOMPILER_CPP_EXAMPLE_TARGET}
	${CMAKE_CURRENT_LIST_DIR}/CPP_Example.cpp
)

target_include_directories(${IGNITECOMPILER_CPP_EXAMPLE_TARGET} PRIVATE
	${CMAKE_CURRENT_LIST_DIR}/../Source
)

target_link_libraries(${IGNITECOMPILER_CPP_EXAMPLE_TARGET} PRIVATE IgniteCompiler)

set_target_properties(${IGNITECOMPILER_CPP_EXAMPLE_TARGET} PROPERTIES
	RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/Example
)

if (MSVC)
	set_property(TARGET ${IGNITECOMPILER_CPP_EXAMPLE_TARGET} PROPERTY
		VS_DEBUGGER_WORKING_DIRECTORY "$<TARGET_FILE_DIR:${IGNITECOMPILER_CPP_EXAMPLE_TARGET}>"
	)
endif()

add_custom_command(TARGET ${IGNITECOMPILER_CPP_EXAMPLE_TARGET} POST_BUILD
	COMMAND ${CMAKE_COMMAND} -E copy_directory
		${CMAKE_CURRENT_LIST_DIR}/Shaders
		$<TARGET_FILE_DIR:${IGNITECOMPILER_CPP_EXAMPLE_TARGET}>/Shaders
	COMMENT "Copying shader examples for C++ example runtime"
)

if (WIN32)
	add_custom_command(TARGET ${IGNITECOMPILER_CPP_EXAMPLE_TARGET} POST_BUILD
		COMMAND ${CMAKE_COMMAND} -E copy_if_different
			$<TARGET_FILE:IgniteCompiler>
			$<TARGET_FILE_DIR:${IGNITECOMPILER_CPP_EXAMPLE_TARGET}>/
		COMMENT "Copying IgniteCompiler runtime next to C++ example"
	)
endif()
